### ISSUE TITLE
Error while making a curl request from the client. 

### ISSUE THREAD

**Issue by manishatGit** [tresata/akka-http-spnego#1]
After launching the **launch-test-server** file
We get the following error while running the curl request from the client. The curl request is: 
curl -k --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt https://localhost:12345/ping

`Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
default-akka.actor.default-dispatcher-5, fatal error: 80: problem unwrapping net record
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
default-akka.actor.default-dispatcher-5, SEND TLSv1.2 ALERT:  fatal, description = internal_error
default-akka.actor.default-dispatcher-5, WRITE: TLSv1.2 Alert, length = 2
default-akka.actor.default-dispatcher-5, called closeInbound()
default-akka.actor.default-dispatcher-5, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
[DEBUG] [02/06/2017 17:44:08.120] [default-akka.actor.default-dispatcher-5] [akka://default/user/StreamSupervisor-0/flow-1-1-unknown-operation] closing output
[DEBUG] [02/06/2017 17:44:08.133] [default-akka.actor.default-dispatcher-7] [akka://default/user/StreamSupervisor-0/flow-1-0-unknown-operation] Aborting tcp connection to /0:0:0:0:0:0:0:1:34531 because of upstream failure: Inbound closed before receiving peer's close_notify: possible truncation attack?
sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1561)
akka.stream.impl.io.TLSActor.akka$stream$impl$io$TLSActor$$doInbound(TLSActor.scala:296)
akka.stream.impl.io.TLSActor$$anonfun$1.apply$mcV$sp(TLSActor.scala:225)
akka.stream.impl.Pump$class.pump(Transfer.scala:199)
akka.stream.impl.io.TLSActor.pump(TLSActor.scala:48)
akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:90)
akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:141)
scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
akka.stream.impl.SubReceive.apply(Transfer.scala:16)
akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:234)
scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
akka.stream.impl.SubReceive.apply(Transfer.scala:16)
akka.stream.impl.SubReceive.apply(Transfer.scala:12)
scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
akka.actor.Actor$class.aroundReceive(Actor.scala:496)
akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:48)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by koertkuipers** [comment]
i can only replicate this if i do:
```curl -k --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt http://myserver:12345/ping```

you sure you are doing https, not http?

**Comment by manishatGit** [comment]
Yes. I am sure about using https. Is there anything else we need to setup apart from installing kerberos and setting up server and client on local machine. I am using ubuntu 15.10 and has configured the kerberos server locally.

**Comment by koertkuipers** [comment]
strange. i get the same errors if i do:
curl -k --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt
http://localhost:12345/ping <https://localhost:12345/ping>

namely:
fatal error: 80: problem unwrapping net record
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

for me pinging localhost doesnt work, i need to ping the full hostname, but
i dont think thats your problem here. everything else looks fine.

**Comment by manishatGit** [comment]
That error was resolved! It was an improper local KDC settings. Thanks for support.
